### ISSUE TITLE
Unable to get method ref for onPointCloudAvailable

### ISSUE THREAD

**Issue by marcodiiga** [googlesamples/tango-examples-java#75]
Since today's last update to Tango Core the `hello_area_description` sample is failing as soon as the learning activity starts.

The error log is the following:

```
E/tango-client-api-jni: Unable to get method ref for onPointCloudAvailable
A/art: art/runtime/check_jni.cc:64] JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception 'java.lang.NoSuchMethodError' thrown in int com.google.atap.tango.TangoJNINative.ConnectListener(int[], com.google.atap.tangoservice.Tango$OnTangoUpdateListener, com.google.atap.tangoservice.TangoPoseData, com.google.atap.tangoservice.TangoXyzIjData, com.google.atap.tangoservice.TangoEvent):-2
A/art: art/runtime/check_jni.cc:64]     in call to GetMethodID
A/art: art/runtime/check_jni.cc:64]     from int com.google.atap.tango.TangoJNINative.ConnectListener(int[], com.google.atap.tangoservice.Tango$OnTangoUpdateListener, com.google.atap.tangoservice.TangoPoseData, com.google.atap.tangoservice.TangoXyzIjData, com.google.atap.tangoservice.TangoEvent)
A/art: art/runtime/check_jni.cc:64] "Thread-437" prio=5 tid=14 Runnable
A/art: art/runtime/check_jni.cc:64]   | group="main" sCount=0 dsCount=0 obj=0x648dc438 self=0x49b8d4e0
A/art: art/runtime/check_jni.cc:64]   | sysTid=13096 nice=0 cgrp=apps sched=0/0 handle=0x49b90008
A/art: art/runtime/check_jni.cc:64]   | state=R schedstat=( 11150250 3312333 23 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/check_jni.cc:64]   | stack=0x49d68000-0x49d6c000 stackSize=1040KB
A/art: art/runtime/check_jni.cc:64]   native: art::Thread::DumpStack(std::ostream&) const+87 [0x41626b78] (libart.so)
A/art: art/runtime/check_jni.cc:64]   native: ??? [0x414d28a6] (libart.so)
A/art: art/runtime/check_jni.cc:64]   native: art::JniAbortF(char const*, char const*, ...)+51 [0x414d3254] (libart.so)
A/art: art/runtime/check_jni.cc:64]   native: ??? [0x414d517c] (libart.so)
A/art: art/runtime/check_jni.cc:64]   native: ??? [0x414d53e6] (libart.so)
A/art: art/runtime/check_jni.cc:64]   native: ??? [0x414d80fa] (libart.so)
A/art: art/runtime/check_jni.cc:64]   native: Java_com_google_atap_tango_TangoJNINative_ConnectListener+843 [0x49c18270] (libtango_client_api.so)
A/art: art/runtime/check_jni.cc:64]   at com.google.atap.tango.TangoJNINative.ConnectListener(Native method)
A/art: art/runtime/check_jni.cc:64]   at com.google.atap.tangoservice.Tango.connectListener(Tango.java:451)
A/art: art/runtime/check_jni.cc:64]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.setUpTangoListeners(HelloAreaDescriptionActivity.java:228)
A/art: art/runtime/check_jni.cc:64]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.access$500(HelloAreaDescriptionActivity.java:47)
A/art: art/runtime/check_jni.cc:64]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity$1.run(HelloAreaDescriptionActivity.java:102)
A/art: art/runtime/check_jni.cc:64]   - locked <0x648c77b0> (a com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity)
A/art: art/runtime/check_jni.cc:64]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/check_jni.cc:64] 
A/art: art/runtime/runtime.cc:203] Runtime aborting...
A/art: art/runtime/runtime.cc:203] Aborting thread:
A/art: art/runtime/runtime.cc:203] "Thread-437" prio=5 tid=14 Runnable
A/art: art/runtime/runtime.cc:203]   | group="main" sCount=0 dsCount=0 obj=0x648dc438 self=0x49b8d4e0
A/art: art/runtime/runtime.cc:203]   | sysTid=13096 nice=0 cgrp=apps sched=0/0 handle=0x49b90008
A/art: art/runtime/runtime.cc:203]   | state=R schedstat=( 33245249 11359917 91 ) utm=2 stm=1 core=1 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x49d68000-0x49d6c000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: art::Thread::DumpStack(std::ostream&) const+87 [0x41626b78] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x4161ec62] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::Runtime::Abort()+79 [0x4161f204] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::LogMessage::~LogMessage()+507 [0x414ca89c] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d2ad4] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::JniAbortF(char const*, char const*, ...)+51 [0x414d3254] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d517c] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d53e6] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d80fa] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: Java_com_google_atap_tango_TangoJNINative_ConnectListener+843 [0x49c18270] (libtango_client_api.so)
A/art: art/runtime/runtime.cc:203]   at com.google.atap.tango.TangoJNINative.ConnectListener(Native method)
A/art: art/runtime/runtime.cc:203]   at com.google.atap.tangoservice.Tango.connectListener(Tango.java:451)
A/art: art/runtime/runtime.cc:203]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.setUpTangoListeners(HelloAreaDescriptionActivity.java:228)
A/art: art/runtime/runtime.cc:203]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.access$500(HelloAreaDescriptionActivity.java:47)
A/art: art/runtime/runtime.cc:203]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity$1.run(HelloAreaDescriptionActivity.java:102)
A/art: art/runtime/runtime.cc:203]   - locked <0x648c77b0> (a com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] Pending exception java.lang.NoSuchMethodError thrown by 'int com.google.atap.tango.TangoJNINative.ConnectListener(int[], com.google.atap.tangoservice.Tango$OnTangoUpdateListener, com.google.atap.tangoservice.TangoPoseData, com.google.atap.tangoservice.TangoXyzIjData, com.google.atap.tangoservice.TangoEvent):-2'
A/art: art/runtime/runtime.cc:203] java.lang.NoSuchMethodError: no non-static method "Lcom/projecttango/examples/java/helloareadescription/HelloAreaDescriptionActivity$2;.onPointCloudAvailable(Lcom/google/atap/tangoservice/TangoPointCloudData;)V"
A/art: art/runtime/runtime.cc:203]   at int com.google.atap.tango.TangoJNINative.ConnectListener(int[], com.google.atap.tangoservice.Tango$OnTangoUpdateListener, com.google.atap.tangoservice.TangoPoseData, com.google.atap.tangoservice.TangoXyzIjData, com.google.atap.tangoservice.TangoEvent) (TangoJNINative.java:-2)
A/art: art/runtime/runtime.cc:203]   at void com.google.atap.tangoservice.Tango.connectListener(java.util.List, com.google.atap.tangoservice.Tango$OnTangoUpdateListener) (Tango.java:451)
A/art: art/runtime/runtime.cc:203]   at void com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.setUpTangoListeners() (HelloAreaDescriptionActivity.java:228)
A/art: art/runtime/runtime.cc:203]   at void com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.access$500(com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity) (HelloAreaDescriptionActivity.java:47)
A/art: art/runtime/runtime.cc:203]   at void com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity$1.run() (HelloAreaDescriptionActivity.java:102)
A/art: art/runtime/runtime.cc:203]   at void java.lang.Thread.run() (Thread.java:811)
A/art: art/runtime/runtime.cc:203] Dumping all threads without appropriate locks held: thread list lock mutator lock
A/art: art/runtime/runtime.cc:203] All threads:
A/art: art/runtime/runtime.cc:203] DALVIK THREADS (14):
A/art: art/runtime/runtime.cc:203] "main" prio=5 tid=1 Native
A/art: art/runtime/runtime.cc:203]   | group="main" sCount=0 dsCount=0 obj=0x646d9b70 self=0x416d8ea8
A/art: art/runtime/runtime.cc:203]   | sysTid=12968 nice=0 cgrp=apps sched=0/0 handle=0x40022154
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 333231391 221460189 1432 ) utm=16 stm=16 core=0 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0xbe3c4000-0xbe3c8000 stackSize=8MB
A/art: art/runtime/runtime.cc:203]   native: android::Looper::pollOnce(int, int*, int*, void**)+92 [0x400c294d] (libutils.so)
A/art: art/runtime/runtime.cc:203]   native: android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22 [0x4016b331] (libandroid_runtime.so)
A/art: art/runtime/runtime.cc:203]   native: oatexec+18086364 [0x634f99dc] (system@framework@boot.oat)
A/art: art/runtime/runtime.cc:203]   at android.os.MessageQueue.nativePollOnce(Native method)
A/art: art/runtime/runtime.cc:203]   at android.os.MessageQueue.next(MessageQueue.java:138)
A/art: art/runtime/runtime.cc:203]   at android.os.Looper.loop(Looper.java:123)
A/art: art/runtime/runtime.cc:203]   at android.app.ActivityThread.main(ActivityThread.java:5030)
A/art: art/runtime/runtime.cc:203]   at java.lang.reflect.Method.invoke(Native method)
A/art: art/runtime/runtime.cc:203]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
A/art: art/runtime/runtime.cc:203]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Thread pool worker 0" prio=5 tid=2 Native (still starting up)
A/art: art/runtime/runtime.cc:203]   | group="" sCount=0 dsCount=0 obj=0x00000000 self=0x43eba6a8
A/art: art/runtime/runtime.cc:203]   | sysTid=12974 nice=0 cgrp=apps sched=0/0 handle=0x43ebe4c8
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 189082 0 6 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x43d79000-0x43d7d000 stackSize=1024KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x42731dcc] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Thread pool worker 1" prio=5 tid=3 Native (still starting up)
A/art: art/runtime/runtime.cc:203]   | group="" sCount=0 dsCount=0 obj=0x00000000 self=0x47030fe0
A/art: art/runtime/runtime.cc:203]   | sysTid=12975 nice=0 cgrp=apps sched=0/0 handle=0x43ebe8d8
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 144833 0 6 ) utm=0 stm=0 core=3 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47136000-0x4713a000 stackSize=1024KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x42731dcc] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Thread pool worker 2" prio=5 tid=4 Native (still starting up)
A/art: art/runtime/runtime.cc:203]   | group="" sCount=0 dsCount=0 obj=0x00000000 self=0x4712c7b8
A/art: art/runtime/runtime.cc:203]   | sysTid=12976 nice=0 cgrp=apps sched=0/0 handle=0x4712bc88
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 90250 23166 3 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47236000-0x4723a000 stackSize=1024KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x42731dcc] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Signal Catcher" daemon prio=5 tid=5 WaitingInMainSignalCatcherLoop
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x6486dcc8 self=0x416dee10
A/art: art/runtime/runtime.cc:203]   | sysTid=12977 nice=0 cgrp=apps sched=0/0 handle=0x4712cb40
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 410250 0 1 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47336000-0x4733a000 stackSize=1016KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41622ca7] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::SignalCatcher::WaitForSignal(art::Thread*, art::SignalSet&)+46 [0x4162301b] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::SignalCatcher::Run(void*)+172 [0x416245b9] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: __thread_entry+72 [0x400451b0] (libc.so)
A/art: art/runtime/runtime.cc:203]   native: pthread_create+240 [0x40045348] (libc.so)
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "JDWP" daemon prio=5 tid=6 WaitingInMainDebuggerLoop
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x6486dab0 self=0x43ec2bc8
A/art: art/runtime/runtime.cc:203]   | sysTid=12978 nice=0 cgrp=apps sched=0/0 handle=0x416df090
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 10013503 53042915 95 ) utm=0 stm=0 core=0 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47434000-0x47438000 stackSize=1016KB
A/art: art/runtime/runtime.cc:203]   native: art::JDWP::JdwpState::Run()+366 [0x415737ef] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41574ae3] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: __thread_entry+72 [0x400451b0] (libc.so)
A/art: art/runtime/runtime.cc:203]   native: pthread_create+240 [0x40045348] (libc.so)
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "ReferenceQueueDaemon" daemon prio=5 tid=7 Waiting
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x6486db50 self=0x43ebf9a8
A/art: art/runtime/runtime.cc:203]   | sysTid=12979 nice=0 cgrp=apps sched=0/0 handle=0x43ebfc28
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 83667 0 1 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47532000-0x47536000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41487dd4] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   at java.lang.Object.wait(Native method)
A/art: art/runtime/runtime.cc:203]   - waiting on <0x600c2780> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
A/art: art/runtime/runtime.cc:203]   at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
A/art: art/runtime/runtime.cc:203]   - locked <0x600c2780> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "FinalizerDaemon" daemon prio=5 tid=8 Waiting
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x64865d30 self=0x4712d510
A/art: art/runtime/runtime.cc:203]   | sysTid=12980 nice=0 cgrp=apps sched=0/0 handle=0x4712d790
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 53750 0 2 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47636000-0x4763a000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41487dd4] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   at java.lang.Object.wait(Native method)
A/art: art/runtime/runtime.cc:203]   - waiting on <0x60a82618> (a java.lang.ref.ReferenceQueue)
A/art: art/runtime/runtime.cc:203]   at java.lang.Object.wait(Object.java:411)
A/art: art/runtime/runtime.cc:203]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
A/art: art/runtime/runtime.cc:203]   - locked <0x60a82618> (a java.lang.ref.ReferenceQueue)
A/art: art/runtime/runtime.cc:203]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
A/art: art/runtime/runtime.cc:203]   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "FinalizerWatchdogDaemon" daemon prio=5 tid=9 Waiting
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x64866f48 self=0x4712dfe8
A/art: art/runtime/runtime.cc:203]   | sysTid=12981 nice=0 cgrp=apps sched=0/0 handle=0x4712e268
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 39250 0 1 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x4773a000-0x4773e000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41487dd4] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   at java.lang.Object.wait(Native method)
A/art: art/runtime/runtime.cc:203]   - waiting on <0x60a89fc0> (a java.lang.Daemons$FinalizerWatchdogDaemon)
A/art: art/runtime/runtime.cc:203]   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:233)
A/art: art/runtime/runtime.cc:203]   - locked <0x60a89fc0> (a java.lang.Daemons$FinalizerWatchdogDaemon)
A/art: art/runtime/runtime.cc:203]   at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:210)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "HeapTrimmerDaemon" daemon prio=5 tid=10 Waiting
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x648680f8 self=0x4712eb30
A/art: art/runtime/runtime.cc:203]   | sysTid=12982 nice=0 cgrp=apps sched=0/0 handle=0x4712ee30
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 38083 0 1 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x4783e000-0x47842000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41487dd4] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   at java.lang.Object.wait(Native method)
A/art: art/runtime/runtime.cc:203]   - waiting on <0x60a89ff0> (a java.lang.Daemons$HeapTrimmerDaemon)
A/art: art/runtime/runtime.cc:203]   at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:299)
A/art: art/runtime/runtime.cc:203]   - locked <0x60a89ff0> (a java.lang.Daemons$HeapTrimmerDaemon)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "GCDaemon" daemon prio=5 tid=11 Waiting
A/art: art/runtime/runtime.cc:203]   | group="system" sCount=0 dsCount=0 obj=0x64869300 self=0x4712f6f8
A/art: art/runtime/runtime.cc:203]   | sysTid=12983 nice=0 cgrp=apps sched=0/0 handle=0x47133998
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 63584 0 1 ) utm=0 stm=0 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47942000-0x47946000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: ??? [0x41487dd4] ([anon:libc_malloc])
A/art: art/runtime/runtime.cc:203]   at java.lang.Object.wait(Native method)
A/art: art/runtime/runtime.cc:203]   - waiting on <0x60a8a010> (a java.lang.Daemons$GCDaemon)
A/art: art/runtime/runtime.cc:203]   at java.lang.Daemons$GCDaemon.run(Daemons.java:330)
A/art: art/runtime/runtime.cc:203]   - locked <0x60a8a010> (a java.lang.Daemons$GCDaemon)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Binder_1" prio=5 tid=12 Native
A/art: art/runtime/runtime.cc:203]   | group="main" sCount=0 dsCount=0 obj=0x64870418 self=0x47134718
A/art: art/runtime/runtime.cc:203]   | sysTid=12984 nice=0 cgrp=apps sched=0/0 handle=0x471344d0
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 2738665 4193166 17 ) utm=0 stm=0 core=1 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47b44000-0x47b48000 stackSize=1016KB
A/art: art/runtime/runtime.cc:203]   native: android::IPCThreadState::talkWithDriver(bool)+140 [0x400f13ed] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: android::IPCThreadState::getAndExecuteCommand()+6 [0x400f1af7] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: android::IPCThreadState::joinThreadPool(bool)+48 [0x400f1b8d] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x400f59a9] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: android::Thread::_threadLoop(void*)+216 [0x400c0a59] (libutils.so)
A/art: art/runtime/runtime.cc:203]   native: android::AndroidRuntime::javaThreadShell(void*)+68 [0x4014deb1] (libandroid_runtime.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x400c058b] (libutils.so)
A/art: art/runtime/runtime.cc:203]   native: __thread_entry+72 [0x400451b0] (libc.so)
A/art: art/runtime/runtime.cc:203]   native: pthread_create+240 [0x40045348] (libc.so)
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Binder_2" prio=5 tid=13 Native
A/art: art/runtime/runtime.cc:203]   | group="main" sCount=0 dsCount=0 obj=0x64870570 self=0x471356a8
A/art: art/runtime/runtime.cc:203]   | sysTid=12985 nice=0 cgrp=apps sched=0/0 handle=0x47135460
A/art: art/runtime/runtime.cc:203]   | state=S schedstat=( 3763254 3662332 21 ) utm=0 stm=0 core=1 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x47c42000-0x47c46000 stackSize=1016KB
A/art: art/runtime/runtime.cc:203]   native: android::IPCThreadState::talkWithDriver(bool)+140 [0x400f13ed] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: android::IPCThreadState::getAndExecuteCommand()+6 [0x400f1af7] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: android::IPCThreadState::joinThreadPool(bool)+48 [0x400f1b8d] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x400f59a9] (libbinder.so)
A/art: art/runtime/runtime.cc:203]   native: android::Thread::_threadLoop(void*)+216 [0x400c0a59] (libutils.so)
A/art: art/runtime/runtime.cc:203]   native: android::AndroidRuntime::javaThreadShell(void*)+68 [0x4014deb1] (libandroid_runtime.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x400c058b] (libutils.so)
A/art: art/runtime/runtime.cc:203]   native: __thread_entry+72 [0x400451b0] (libc.so)
A/art: art/runtime/runtime.cc:203]   native: pthread_create+240 [0x40045348] (libc.so)
A/art: art/runtime/runtime.cc:203]   (no managed stack frames)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] "Thread-437" prio=5 tid=14 Native
A/art: art/runtime/runtime.cc:203]   | group="main" sCount=0 dsCount=0 obj=0x648dc438 self=0x49b8d4e0
A/art: art/runtime/runtime.cc:203]   | sysTid=13096 nice=0 cgrp=apps sched=0/0 handle=0x49b90008
A/art: art/runtime/runtime.cc:203]   | state=R schedstat=( 129179162 23876504 194 ) utm=5 stm=7 core=2 HZ=100
A/art: art/runtime/runtime.cc:203]   | stack=0x49d68000-0x49d6c000 stackSize=1040KB
A/art: art/runtime/runtime.cc:203]   native: art::Thread::DumpStack(std::ostream&) const+87 [0x41626b78] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::ThreadList::DumpLocked(std::ostream&)+69 [0x41631b16] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x4161ed14] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::Runtime::Abort()+79 [0x4161f204] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::LogMessage::~LogMessage()+507 [0x414ca89c] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d2ad4] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: art::JniAbortF(char const*, char const*, ...)+51 [0x414d3254] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d517c] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d53e6] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: ??? [0x414d80fa] (libart.so)
A/art: art/runtime/runtime.cc:203]   native: Java_com_google_atap_tango_TangoJNINative_ConnectListener+843 [0x49c18270] (libtango_client_api.so)
A/art: art/runtime/runtime.cc:203]   at com.google.atap.tango.TangoJNINative.ConnectListener(Native method)
A/art: art/runtime/runtime.cc:203]   at com.google.atap.tangoservice.Tango.connectListener(Tango.java:451)
A/art: art/runtime/runtime.cc:203]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.setUpTangoListeners(HelloAreaDescriptionActivity.java:228)
A/art: art/runtime/runtime.cc:203]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity.access$500(HelloAreaDescriptionActivity.java:47)
A/art: art/runtime/runtime.cc:203]   at com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity$1.run(HelloAreaDescriptionActivity.java:102)
A/art: art/runtime/runtime.cc:203]   - locked <0x648c77b0> (a com.projecttango.examples.java.helloareadescription.HelloAreaDescriptionActivity)
A/art: art/runtime/runtime.cc:203]   at java.lang.Thread.run(Thread.java:811)
A/art: art/runtime/runtime.cc:203] 
A/art: art/runtime/runtime.cc:203] 
A/libc: Fatal signal 6 (SIGABRT) at 0x000032a8 (code=-6), thread 13096 (Thread-437)
```

**Comment by trippedout** [comment]
I had same error, so I made sure to git pull latest code from this repo and update latest core (both vega) and the errors went away. make sure to clean and rebuild the apks too

**Comment by marcodiiga** [comment]
@trippedout Thanks, that fixed the issue. Closing this down.
