### ISSUE TITLE
Tango Core crashes 

### ISSUE THREAD

**Issue by timfreiheit** [googlesamples/tango-examples-java#81]
Since the latest updates im only getting crashes on my app and the Sample Apps

```

10-31 15:17:43.908 3597-3620/com.projecttango.experiments.planefittingsample E/tango_client_api: virtual void TangoMortician::binderDied(const android::wp<android::IBinder>&): Internal Error: TangoService died.
10-31 15:17:43.908 3597-3641/com.projecttango.experiments.planefittingsample E/tango: TangoClient.cc:679 Tango Service binder transaction failed! Transaction type code = 1, status = -32.
10-31 15:17:43.909 3597-3642/com.projecttango.experiments.planefittingsample E/tango_client_api: TangoErrorType TangoService_connect(void*, TangoConfig): Internal Error: Connect failed internally: -1
10-31 15:17:43.910 3597-3642/com.projecttango.experiments.planefittingsample E/PlaneFittingActivity: Tango exception!
                                                                                                     com.google.atap.tangoservice.TangoErrorException
                                                                                                         at com.google.atap.tangoservice.Tango.throwTangoExceptionIfNeeded(Tango.java:840)
                                                                                                         at com.google.atap.tangoservice.Tango.connect(Tango.java:435)
                                                                                                         at com.projecttango.examples.java.planefitting.PlaneFittingActivity$1.run(PlaneFittingActivity.java:122)
                                                                                                         at java.lang.Thread.run(Thread.java:811)

```

The Tango Core crashed and in some cases, the tango device restarts.
Im testing this with the "Project Tango Development Kit"

**Comment by darnabas** [comment]
Just curious, were you able to resolve this issue?

**Comment by timfreiheit** [comment]
Thank you. This worked for me too
