### ISSUE TITLE
Error when trying to export ADF File

### ISSUE THREAD

**Issue by wirthual** [googlesamples/tango-examples-java#85]
Hello everybody,

when I try to export a ADF File to SD-Card i get the following message:
I call: `mTango.exportAreaDescriptionFile(uuid,getExternalFilesDir(null).getAbsolutePath()+"Test.adf");`
Same when I do this:
```
 Intent exportIntent = new Intent();
        exportIntent.setClassName(INTENT_CLASSPACKAGE, INTENT_IMPORTEXPORT_CLASSNAME);
        exportIntent.putExtra(EXTRA_KEY_SOURCEUUID,uuid);
        exportIntent.putExtra(EXTRA_KEY_DESTINATIONFILE, getExternalFilesDir(null).getAbsolutePath()+"Test.adf");
        startActivityForResult(exportIntent, Tango.TANGO_INTENT_ACTIVITYCODE);
```
`FATAL EXCEPTION: main
                                                 Process: com.google.tango, PID: 8075
                                                 java.util.MissingFormatArgumentException: Format specifier: 2$s
                                                     at java.util.Formatter.getArgument(Formatter.java:1111)
                                                     at java.util.Formatter.doFormat(Formatter.java:1076)
                                                     at java.util.Formatter.format(Formatter.java:1042)
                                                     at java.util.Formatter.format(Formatter.java:1011)
                                                     at java.lang.String.format(String.java:1964)
                                                     at java.lang.String.format(String.java:1938)
                                                     at com.google.atap.tango.RequestImportExportDialog.getColoredSpannedString(RequestImportExportDialog.java:138)
                                                     at com.google.atap.tango.RequestImportExportDialog.onCreateView(RequestImportExportDialog.java:92)
                                                     at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                     at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                                                     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5030)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
11-22 18:08:04.916 908-1171/? W/ActivityManager:   Force finishing activity com.google.tango/com.google.atap.tango.RequestImportExportActivity
11-22 18:08:04.917 908-1171/? W/ActivityManager:   Force finishing activity com.wirthual.editsys/.StartActivity
11-22 18:08:05.417 908-954/? W/ActivityManager: Activity pause timeout for ActivityRecord{65317f40 u0 com.google.tango/com.google.atap.tango.RequestImportExportActivity t7 f}`

Anyone a idea?

**Comment by SetoKaiba** [comment]
It's the problem of Zaniah Tango Core. Uninstall the update of Tango Core could be a temporary workaround.

**Comment by wirthual** [comment]
It seems like it is connected to language settings. If language is set to english, this error does not occur. In german it does.
